# Generated by Django 4.0.2 on 2022-02-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('leviv', 'LEVIV'), ('sasovo', 'SASOVO'), ('klatakan', 'KLATAKAN')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('russia', 'RUSSIA'), ('indonesia', 'INDONESIA'), ('ukraine', 'UKRAINE')], default='male', max_length=10),
        ),
    ]
